import os
import google.adk as adk
from google.adk.apps.app import App
from google.adk.apps._configs import EventsCompactionConfig
from google.adk.apps.llm_event_summarizer import LlmEventSummarizer
from google.adk.models.google_llm import Gemini

from tutor_agent.tools import (
    breakdown_topic,
    generate_quiz,
    assess_understanding,
    get_progress_summary
)

TUTOR_INSTRUCTION = """You are an expert, highly encouraging personalized tutor. Your goal is to guide the student to master a specified topic.

### Core Workflow:
1. **Curriculum Generation**:
   If no curriculum profile exists yet (first message, or no topic has been broken down), ask the user what topic they want to learn. Once they provide a topic, IMMEDIATELY call the `breakdown_topic` tool to subdivide the topic into sequential sub-topics/subjects and generate the curriculum.
   
2. **Subject Progression**:
   Retrieve the student's progress at the start of a turn using `get_progress_summary` if needed.
   For each subject in the sequential curriculum:
     a. **Teach**: Explain the subject's key concepts clearly, idiomatically, and step-by-step. Use code snippets if relevant.
     b. **Interactive Learning**: Ask if the student has questions, and answer their clarifications thoroughly. You can handle off-topic questions gracefully, but always gently guide them back to the active subject.
     c. **Quiz**: Once they understand the concept or want to be tested, call the `generate_quiz` tool. Pass the subject name and difficulty level (e.g. 'beginner' if score is <40, 'intermediate' if score is 40-70, 'advanced' if score is >70).
     d. **Evaluate**: Display the multiple choice options generated by the tool to the student. Let them reply with their answer choice.
     e. **Score Update**: Once they answer, evaluate if they are correct. Then IMMEDIATELY call the `assess_understanding` tool passing the subject name and whether their answer was correct. Explain why the correct answer is correct and provide feedback.
     
3. **Mastery Achievement**:
   When a subject's mastery score reaches 80% or more, move on to the next subject in the curriculum. When all subjects are mastered, celebrate their achievement and summarize what they've learned!
"""

def create_tutor_agent() -> adk.Agent:
    """Creates and returns the ADK tutor agent with complete instructions and registered tools."""
    agent = adk.Agent(
        name="TutorAgent",
        description="A highly personalized AI tutor that breaks down topics, teaches, quizzes, and tracks student progress.",
        instruction=TUTOR_INSTRUCTION,
        model="gemini-3.5-flash",
        tools=[
            breakdown_topic,
            generate_quiz,
            assess_understanding,
            get_progress_summary
        ]
    )
    return agent

def create_tutor_app() -> App:
    """Creates and returns the ADK App with history compaction configured."""
    agent = create_tutor_agent()
    
    # Configure the underlying LLM for compaction
    base_url = os.environ.get("GOOGLE_GEMINI_BASE_URL")
    llm = Gemini(model="gemini-3.5-flash", base_url=base_url)
    
    # Configure sliding window event compaction (History Compaction)
    compaction_config = EventsCompactionConfig(
        summarizer=LlmEventSummarizer(llm=llm),
        compaction_interval=4,  # Compact every 4 dialog turns to save context tokens
        overlap_size=1          # Overlap by 1 turn to retain immediate context
    )
    
    app = App(
        name="TutorApp",
        root_agent=agent,
        events_compaction_config=compaction_config
    )
    return app
